django101/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import social

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', 		include('social.urls', namespace ='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.conf.urls import include, url
from social import views

urlpatterns = [
	url(r'login/', 	views.social_login, name = 'login'),
	url(r'$^',		views.index, name = 'index'	),
	url(r'home/', 	views.home, name = 'home'),
	url(r'stream/', views.stream, name = 'stream'),
	url(r'post/add/', views.add_post, name="add_post"),
	url(r'playlist/add/', views.add_playlist, name="add_playlist"),
	url(r'song/add/', views.add_post, name="add_song"),
	url(r'comment/add/', views.add_comment, name='add_comment'),
	url(r'json/playlist/(?P<playlist_id>[0-9]+)/$', views.get_json_playlist, name='get_json_playlist'),
	url(r'playlist/(?P<playlist_id>[0-9]+)/$', views.get_playlist, name='get_playlist'),
	url(r'playlist/addSong/', views.add_song_to_playlist, name="add_song_to_playlist"),
	url(r'playlist/delete/',   views.delete_playlist, name="delete_playlist"),
]

social/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
	text = models.TextField()
	poster = models.ForeignKey(User)
	date_time = models.DateTimeField(auto_now=True)
	photo = models.ImageField(null = True, blank=True)

class Comment(models.Model):
	text = models.TextField()
	poster = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	date_time = models.DateTimeField(auto_now = True)
	class Meta:
		ordering = ['-date_time']

		
		
		
		
class Genre(models.Model):
	name = models.CharField(max_length = 50)
	def __str__(self):
		return self.name
		
		


class Artist(models.Model):
	name = models.TextField()
	profilePicture = models.ImageField()
	def __str__(self):
		return self.name
	
class Album(models.Model):
	name = models.CharField(max_length = 50)
	savedBy = models.ManyToManyField(User)
	artist 	= models.ForeignKey(Artist)
	genre 	= models.ManyToManyField(Genre)
	profilePicture = models.ImageField()
	lastPlayed = models.DateTimeField(auto_now = True)
	def __str__(self):
		return self.name

			

	
class Song(models.Model):
	name	= models.CharField(max_length = 50)
	artist	= models.ForeignKey(Artist)
	genre 	= models.ManyToManyField(Genre)
	album	= models.ForeignKey(Album)
	audioFile = models.FileField(upload_to="musicDatabase/")
	lastPlayed = models.DateTimeField()
	songLength = models.FloatField()
	def __str__(self):
		return self.name
		
	

class Playlist(models.Model):
	name = models.CharField(max_length = 50)
	owner = models.ForeignKey('auth.User')
	songs = models.ManyToManyField(Song, blank= True, null = True)
	timeAdded = models.DateTimeField(auto_now = True)
	cover  = models.ImageField(default='/media/1.jpg')
	class Meta:
		ordering = ['-timeAdded']
	def __str__(self):
		return self.name	
	


class UserProfile(models.Model):
	user = models.ForeignKey(User)
	playlists = models.ManyToManyField(Playlist)
	friends = models.ManyToManyField(User, related_name = 'UserProfile')
	albums = models.ManyToManyField(Album)
	allSongs = models.ManyToManyField(Song)
	profilePicture = models.ImageField()
	def __str__(self):
		return self.name

social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


import json

from social.models import Post
from social.models import Comment, Post # put this at the top with the other imports
from social.models import Playlist, Artist, Album, Song, UserProfile


# Create your views here.

def index(request):
	return render(request, 'social/index.html')
	
def social_login(request):
   check = _check_post_request(request, ['username', 'password'])
   if check[0]:
       user = authenticate(username=request.POST['username'], password=request.POST['password']) 
       if user is not None:
           login(request, user)
           return HttpResponseRedirect(reverse('social:stream'))
       else:
           return HttpResponseBadRequest("The combination of username and password does not exist.")
   else:
       return HttpResponseBadRequest(check[1])
		
@login_required
def stream(request):
	if request.method == 'GET':
		userPlaylists = Playlist.objects.filter(owner=request.user).order_by('-timeAdded')
		user = UserProfile.objects.filter(user=request.user)
		songResults = []
	elif request.method == 'POST':
		check = _check_post_request(request, ['search_terms'])
		if check[0]:
			user = UserProfile.objects.filter(user=request.user)
			userPlaylists = Playlist.objects.filter(owner=request.user).order_by('-timeAdded')
			search_term = request.POST['search_terms']
			songResults = Song.objects.filter(name__icontains=search_term) | Song.objects.filter(artist__name__icontains=search_term) | Song.objects.filter(album__name__icontains=search_term)
		else:
			return HttpResponseBadRequest(check[1])
	return render(request, 'social/stream.html', {'userPlaylists': userPlaylists, 'user':user, 'songResults': songResults})

@login_required
def home(request):
    if request.method == 'GET':
        posts = Post.objects.all()
    elif request.method == 'POST':
        check = _check_post_request(request, ['search_terms'])
        if check[0]:
            search_term = request.POST['search_terms']
            posts = Post.objects.filter(text__icontains=search_term)
        else:
            return HttpResponseBadRequest(check[1])
    posts = posts.order_by('-date_time')
    return render(request, 'social/home.html', {'posts': posts})
	
@login_required
def add_song_to_playlist(request):
	print('hi')
	playlistID = request.POST['playlistID']
	playlist = Playlist.objects.get(pk=playlistID)
	songID = request.POST['songID']
	
	print(songID)
	print(playlist.id)
	song = Song.objects.get(pk=songID)
	print(song.name)
	print(playlist.name)
	playlist.songs.add(song)
	return HttpResponseRedirect(reverse('social:stream'))
	

@login_required		
def add_playlist(request):
	check = _check_post_request(request, ['text'])
	if check[0]:
		new_playlist = Playlist()
		new_playlist.name = request.POST['text']
		new_playlist.owner = request.username
		new_playlist.save()
		return HttpResponseRedirect(reverse('social:stream'))
	else:
		return HttpResponseBadRequest(check[1]);
	
@login_required
def delete_playlist(request):
	playlistID = request.POST['playlist_id']
	playlist = Playlist.objects.get(pk=playlistID)
	playlist.delete()
	return HttpResponseRedirect(reverse('social:stream'))

@login_required
def add_post(request):
	
	check = _check_post_request(request, ['text'])
	if check[0]:
		new_post = Post()
		new_post.text = request.POST['text']
		new_post.poster = request.user
		if 'photo' in request.FILES and request.FILES['photo'] is not None:
			new_post.photo = request.FILES['photo']
		new_post.save()
		return HttpResponseRedirect(reverse('social:home'))
	else:
		return HttpResponseBadRequest(check[1])

		
@login_required
def add_playlist(request):
	
	check = _check_post_request(request, ['playlistName'])		
	if check[0]:
		new_playlist = Playlist()
		new_playlist.name = request.POST['playlistName']
		new_playlist.owner = request.user
		if 'cover' in request.FILES and request.FILES['cover'] is not None:
			new_playlist.cover = request.FILES['cover']
		new_playlist.save()
		return HttpResponseRedirect(reverse('social:stream'))
	else:
		return HttpResponseBadRequest(check[1])
		
		
@login_required		
def add_comment(request):
	check = _check_post_request(request, ['comment'])
	if check[0]:
		new_comment = Comment()
		new_comment.text = request.POST['comment']
		new_comment.poster = request.user
		try:
			post = Post.objects.get(pk=request.POST['post_id'])
			new_comment.post = post
		except Post.DoesNotExist:
			return HttpResponseBadRequest("There is no Post with id {}".format(request.POST['post_id']))
		new_comment.save()
		return HttpResponseRedirect(reverse('social:home'))
	else:
		return HttpResponseBadRequest(check[1])
		
def _check_post_request(request, keys):
	#check if request method is POST
	if request.method != 'POST':
		return (False, "This method shuld be called with a POST method")
	for key in keys:
		# Check that the key exists
		if key not in request.POST:
			return (False, "The POST request should contain a {} field". format(key))
		# Check that the text is not empty
		if not request.POST[key]:
			return(False, "The {} field cannot be empty!".format(key))
	
	return (True, "Everything is fine")
	
def get_playlist(request, playlist_id):
	playlist = Playlist.objects.get(pk=playlist_id)
	return render(request, 'social/playlist.html', {'playlist': playlist})

def get_json_playlist(request, playlist_id):
	playlist = Playlist.objects.get(pk=playlist_id)
	result = {}
	result['name'] = playlist.name
	result['id'] = playlist.id
	result['coverUrl'] = playlist.cover.url
	
	result['songs'] = []
	for song in playlist.songs.all():
	  song_obj = {}
	  song_obj['id'] = song.id
	  song_obj['name'] = song.name
	  song_obj['artist'] = {'name': song.artist.name, 'id': song.artist.id}
	  song_obj['url'] = song.audioFile.url
	  song_obj['album'] = {'name': song.album.name, 'id': song.album.id}
	  result['songs'].append(song_obj)
	return HttpResponse(json.dumps(result))


	

	

social/templates/social/home.html
<html>
  <head>
    {% load staticfiles %}
    <title> Social </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>

  </head>
  <body>
    <div class='container'>

	
      <!-- New post container -->
	<div class='row'>
		<div class='col-xs-8 col-xs-offset-2'>
			<div class='panel panel-primary' id='new-post'>
				<div class='panel-body'>
					<h1> Write a new post </h1>
					<form action="{% url 'social:add_post' %}" method="post" id='new-post-form' enctype='multipart/form-data'>
					{% csrf_token %}
						<div class='form-group'>
							<textarea class='form-control'name='text' form='new-post-form' required placeholder="Write your post here..."></textarea> 
						</div>
						<div class='form-group'>
							<input id='photo-upload' class='form-control' 
								type='file' name='photo' accept='image/*'>
							</input>
							<label for='photo-upload'>Upload a photo</label>
						</div>
						<button type='submit' class='btn btn-default'>Post</button>
					</form>
				</div>
			</div>
		</div>
		
		
		<!-- Search box -->
		<div class='col-xs-2'>
			<div class='well'>
				<form action="{% url 'social:home' %}" method="post" id='search-bar'>
				{% csrf_token %}
					<div class='form-group'>
						<input type='text' class='form-control' name='search_terms' required placeholder='Search in posts...'>
					</div>
					<button type='submit' class='btn btn-primary'>Search</button>
				</form>
				<a class='btn btn-success' href="{% url 'social:home' %}">Show all</a>
			</div>
		</div>
	</div>
	
	
	
	
      <div class='row'>
        <div class='col-xs-8 col-xs-offset-2'>
          {% for post in posts %}
          <div class='panel panel-default' id="{{post.id}}">
            <div class='panel-heading'>
              <h4>{{post.poster.username}}</h4>
              <h4 class='small'>posted on {{post.date_time}}</h4>
            </div>
            <div class='panel-body'>
				<p class='lead'>{{post.text}}</p>
			</div>
			{% if post.photo %}
			<div class='col-xs-10 col-xs-offset-1'>
				<img class='img-responsive center-block img-rounded' src={{post.photo.url}}/>
			</div>
			{% endif %}
            <div class='row'>
              <div class='col-xs-10 col-xs-offset-1'>
                <ul class='list-group'>
                  {% for comment in post.comment_set.all %}
                  <li class='list-group-item'> 
                    {{comment.text}} - {{comment.poster.username}} ({{comment.date_time}}) 
                  </li>
                  {% endfor %}
                </ul>
                <form action="{% url 'social:add_comment' %}" method="post">
                {% csrf_token %}
                  <div class='form-group'>
                    <input class='form-control' type='text' name='comment' required placeholder="Write your comment here..."/>
                  </div>
                  <input type='hidden' name='post_id' value={{post.id}} />
                  <button class='btn btn-default' type='submit'>Submit</button>
                </form>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>

social/templates/social/index.html
<html>
  <head>
    {% load staticfiles %}
    <title> Welcome to Social! </title>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap.css' %}"></link>
    <link rel="stylesheet" href="{% static 'social/bootstrap-3.3.6-dist/css/bootstrap-theme.css' %}"></link>
  </head>
  <script>//if 'photo' in request.FILES and request.FILES['photo'] is not None:</script
  
  <body role='document'>
  
  
    <div class="container">
	
	
		<div class='jumbotron'>
			<h1> Welcome to Social, the least useful social network! </h1>
		</div>
	  
	  
		<div class='row'>
		
			<div class='col-xs-8 panel panel-default'>
				<div class='panel-body'>
					<p> Social is a minimalistic social network that allows you to share
					writings and pictures with the world. Don't bother with friends, share
					with everyone!
					</p>
				</div>
			</div>
		
		
			<div class='col-xs-4'>
			
				<h2> Please sign in to continue </h2>

				<form action="{% url 'social:login' %}" method="post">
					{% csrf_token %}
					<div class='form-group'>
						<label for="username-input">Username</label>
						<input type="text" class="form-control" required name="username" id="username-input"> 
					</div>

					<div class='form-group'>
						<label for="password-input">Password</label>
						<input type="password"  class="form-control"  required name="password" id="password-input"> 
					</div>
				
					<button type="submit" class="btn btn-primary">Log in</button>
				</form>
			</div>
		
		
		
		
		</div>
		
		
		
		
    </div>
  </body>
</html>

social/templates/social/playlist.html
<html>
  <head>
    {% load staticfiles %}
  
    <link rel="stylesheet" href="{% static 'social/spotifyDemoCSS.css' %}"></link>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
 </head>
  
  
  <body>
  
  
    <div class="container">
	
	
		
		
		
			
			<div class='contentContainerInner'>
			
			
		
				<div class="playlistContainer">
					{% for song in playlist.songs.all %}
					<div class="songBar" id = "{{playlist.id}}" >
						<div class="songName" >{{song.name}}</div>
						<div class="songArtist"> {{song.artist.name}}</div>
						<div class="songAlbum">{{song.album.name}}</div>
						<div class="songDuration"> {{song.duration}}</div>
						<audio src='{{song.audioFile.url}}' controls></audio>
					</div>
					
					{% endfor %}
				</div>
			
				
			
			</div>
			
		
		
		
		
    </div>
  </body>
</html>